compare : compare.c
	gcc -pthread -Wall -Werror -g -fsanitize=address compare.c -o compare -lm
goBack : goBack.c
	gcc -pthread -Wall -Werror -fsanitize=address goBack.c -o goBack -lm
newCompare : newCompare.c
	gcc -pthread -Wall -Werror -g -fsanitize=address newCompare.c -o newCompare -lm
